
dataset:
  preprocess: False
  train_dataset: 'data/train'
  val_dataset: 'data/test'
  batch_size: 10
  num_workers: 4

model:
  num_channels: 1
  num_of_layers: 17
  criterion: MSELoss
  optim: 
    type: Adam
    lr: 1e-3

train:
  epoch: 50 
  mode: S
  noiseL: 25
  noiseLB: [0,55]
  lr_decay: 30
  
val:
  noiseL: 25 

log:
  path: 

